use cip_core_confidence::ConfidenceResult;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

/// One incremental piece of transcribed speech. `is_final` distinguishes a
/// still-changing partial hypothesis from a settled segment, mirroring how
/// streaming speech recognizers typically report results.
///
/// `start_ms`/`end_ms` are on a single consistent clock: milliseconds since
/// the producing `SpeechEngine` started receiving audio for the current
/// capture session (an audio-relative clock, not the system wall clock).
/// Mapping that to service-relative or wall-clock time, if ever needed, is
/// the caller's job - `SpeechEngine` doesn't know when a service started.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TranscriptSegment {
    /// Stable id for this segment, generated by the engine when the
    /// segment is created - both an interim segment and the final segment
    /// it settles into share the same id, so a consumer can tell they're
    /// the same utterance without text-matching.
    pub id: Uuid,
    /// Monotonically increasing per capture session, starting at 0.
    /// Interim revisions of the same segment do not consume a new number.
    pub sequence: u64,
    pub text: String,
    pub is_final: bool,
    pub confidence: ConfidenceResult,
    pub start_ms: u64,
    pub end_ms: u64,
    /// BCP-47-ish language tag (e.g. `"en"`), when the engine can report
    /// one. Never guessed - `None` when the engine doesn't know.
    pub language: Option<String>,
    /// Never invented: `None` unless the engine actually performs speaker
    /// identification (none of Phase 1.2's engines do).
    pub speaker_id: Option<String>,
}

#[derive(Debug, Error)]
pub enum SpeechEngineError {
    #[error("speech engine not initialized")]
    NotInitialized,
    #[error("model not found: {0}")]
    ModelNotFound(String),
    #[error("transcription failed: {0}")]
    TranscriptionFailed(String),
}

/// The provider/adaptor contract for speech-to-text. `core` depends only on
/// this trait; `ai/speech` supplies concrete implementations (a local model
/// first - no cloud dependency is required for CIP to function offline).
///
/// Implementations consume raw audio frames (format/source is an
/// implementation detail negotiated with whatever `AudioEngine` is active -
/// see `core/service::AudioEngine`) and emit `TranscriptSegment`s. Nothing
/// in this trait or its callers may assume a specific model, vendor, or
/// language - see `ai/speech`'s module docs for the Phase 1.2
/// implementations behind it.
pub trait SpeechEngine: Send + Sync {
    fn is_ready(&self) -> bool;

    /// Feed one chunk of raw mono PCM16 audio and receive zero or more
    /// transcript segments produced so far (interim, final, or both).
    fn feed_audio(&mut self, samples: &[i16]) -> Result<Vec<TranscriptSegment>, SpeechEngineError>;

    /// Flush any buffered audio and finalize the current segment.
    fn flush(&mut self) -> Result<Vec<TranscriptSegment>, SpeechEngineError>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use cip_core_confidence::ConfidenceSource;

    struct NullSpeechEngine;

    impl SpeechEngine for NullSpeechEngine {
        fn is_ready(&self) -> bool {
            false
        }
        fn feed_audio(
            &mut self,
            _samples: &[i16],
        ) -> Result<Vec<TranscriptSegment>, SpeechEngineError> {
            Err(SpeechEngineError::NotInitialized)
        }
        fn flush(&mut self) -> Result<Vec<TranscriptSegment>, SpeechEngineError> {
            Ok(vec![])
        }
    }

    #[test]
    fn not_ready_engine_reports_not_initialized() {
        let mut engine = NullSpeechEngine;
        assert!(!engine.is_ready());
        assert!(matches!(
            engine.feed_audio(&[]),
            Err(SpeechEngineError::NotInitialized)
        ));
    }

    #[test]
    fn transcript_segment_carries_a_confidence_result() {
        let segment = TranscriptSegment {
            id: Uuid::new_v4(),
            sequence: 0,
            text: "Romans eight".into(),
            is_final: true,
            confidence: ConfidenceResult::new(0.9, ConfidenceSource::Model, None),
            start_ms: 0,
            end_ms: 500,
            language: Some("en".into()),
            speaker_id: None,
        };
        assert!(segment.confidence.is_auto_acceptable());
    }
}
