use cip_core_confidence::ConfidenceResult;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

/// One incremental piece of transcribed speech. `is_final` distinguishes a
/// still-changing partial hypothesis from a settled segment, mirroring how
/// streaming speech recognizers typically report results.
///
/// `start_ms`/`end_ms` are on a single consistent clock: milliseconds since
/// the producing `SpeechEngine` started receiving audio for the current
/// capture session (an audio-relative clock, not the system wall clock).
/// Mapping that to service-relative or wall-clock time, if ever needed, is
/// the caller's job - `SpeechEngine` doesn't know when a service started.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TranscriptSegment {
    /// Stable id for this segment, generated by the engine when the
    /// segment is created - both an interim segment and the final segment
    /// it settles into share the same id, so a consumer can tell they're
    /// the same utterance without text-matching.
    pub id: Uuid,
    /// Monotonically increasing per capture session, starting at 0.
    /// Interim revisions of the same segment do not consume a new number.
    pub sequence: u64,
    pub text: String,
    pub is_final: bool,
    pub confidence: ConfidenceResult,
    pub start_ms: u64,
    pub end_ms: u64,
    /// BCP-47-ish language tag (e.g. `"en"`), when the engine can report
    /// one. Never guessed - `None` when the engine doesn't know.
    pub language: Option<String>,
    /// Never invented: `None` unless the engine actually performs speaker
    /// identification (none of Phase 1.2's engines do).
    pub speaker_id: Option<String>,
}

#[derive(Debug, Error)]
pub enum SpeechEngineError {
    #[error("speech engine not initialized")]
    NotInitialized,
    #[error("model not found: {0}")]
    ModelNotFound(String),
    #[error("transcription failed: {0}")]
    TranscriptionFailed(String),
}

/// The provider/adaptor contract for speech-to-text. `core` depends only on
/// this trait; `ai/speech` supplies concrete implementations (a local model
/// first - no cloud dependency is required for CIP to function offline).
///
/// Implementations consume raw audio frames (format/source is an
/// implementation detail negotiated with whatever `AudioEngine` is active -
/// see `core/service::AudioEngine`) and emit `TranscriptSegment`s. Nothing
/// in this trait or its callers may assume a specific model, vendor, or
/// language - see `ai/speech`'s module docs for the Phase 1.2
/// implementations behind it.
pub trait SpeechEngine: Send + Sync {
    fn is_ready(&self) -> bool;

    /// Feed one chunk of raw mono PCM16 audio and receive zero or more
    /// transcript segments produced so far (interim, final, or both).
    fn feed_audio(&mut self, samples: &[i16]) -> Result<Vec<TranscriptSegment>, SpeechEngineError>;

    /// Flush any buffered audio and finalize the current segment.
    fn flush(&mut self) -> Result<Vec<TranscriptSegment>, SpeechEngineError>;

    /// The sample rate (Hz) `feed_audio` requires its input already
    /// resampled to, if this engine has a fixed requirement. `None`
    /// (the default) means the engine accepts whatever rate it is given -
    /// true of every engine that does not actually process sample
    /// content (`NullSpeechEngine`, `ScriptedSpeechEngine`).
    ///
    /// `AudioEngine` implementations deliver chunks at the capture
    /// device's own native rate and never resample themselves (see
    /// `integrations/audio`'s module docs) - a caller feeding a real
    /// engine's `feed_audio` is responsible for converting from the
    /// chunk's reported rate to this one first. Phase 3.8.6 added this
    /// method after finding that call site was not converting at all.
    fn required_sample_rate_hz(&self) -> Option<u32> {
        None
    }

    /// Whether the most recent `feed_audio` call actually ran the
    /// engine's real inference pass, as opposed to merely buffering audio
    /// toward a future one. `false` by default - only an engine that
    /// internally batches audio before inferring (only
    /// `WhisperSpeechEngine` does, today) needs to override this.
    ///
    /// Phase 3.8.7.3: added after a real Windows session showed
    /// misleadingly high "inferences attempted" counts - every
    /// `feed_audio` call was counted as an attempt even though most of
    /// them (per `WhisperSpeechEngine`'s own ~3s buffering window) never
    /// touch whisper.cpp at all. A caller that wants an honest count
    /// checks this after each `feed_audio` call rather than assuming
    /// every call is an inference.
    fn last_feed_triggered_inference(&self) -> bool {
        false
    }

    /// Whether the most recent `feed_audio` call's fully-buffered window
    /// was classified as silence by voice-activity detection and skipped
    /// without ever running the engine's real inference pass - distinct
    /// from `last_feed_triggered_inference() == false`, which is also true
    /// for a window that simply hasn't finished buffering yet. `false` by
    /// default - only an engine with its own VAD gate (`WhisperSpeechEngine`,
    /// Phase 5.3) overrides this.
    ///
    /// Phase 5.3: added so a caller can honestly distinguish "no inference
    /// happened yet because the window is still filling" from "a full
    /// window arrived but was near-silent, so inference was deliberately
    /// skipped" - both report `last_feed_triggered_inference() == false`,
    /// but only the latter should count as a real, observable VAD event in
    /// diagnostics.
    fn last_feed_was_silence(&self) -> bool {
        false
    }

    /// Discard any buffered-but-not-yet-inferred audio without running
    /// inference on it. A no-op by default (`NullSpeechEngine`/
    /// `ScriptedSpeechEngine` hold no such buffer).
    ///
    /// Phase 3.8.7.3: used by a real-time caller that has determined its
    /// own backlog of unprocessed audio has grown too stale to be worth
    /// finishing (see `docs/phase-3-8-7-3-audit.md`'s backpressure
    /// design) - clearing the engine's own internal buffer here prevents
    /// splicing fresh, post-recovery audio onto old, now-discontinuous
    /// buffered samples in whatever the engine's next real inference
    /// window turns out to be.
    fn discard_buffered_audio(&mut self) {}
}

#[cfg(test)]
mod tests {
    use super::*;
    use cip_core_confidence::ConfidenceSource;

    struct NullSpeechEngine;

    impl SpeechEngine for NullSpeechEngine {
        fn is_ready(&self) -> bool {
            false
        }
        fn feed_audio(
            &mut self,
            _samples: &[i16],
        ) -> Result<Vec<TranscriptSegment>, SpeechEngineError> {
            Err(SpeechEngineError::NotInitialized)
        }
        fn flush(&mut self) -> Result<Vec<TranscriptSegment>, SpeechEngineError> {
            Ok(vec![])
        }
    }

    #[test]
    fn not_ready_engine_reports_not_initialized() {
        let mut engine = NullSpeechEngine;
        assert!(!engine.is_ready());
        assert!(matches!(
            engine.feed_audio(&[]),
            Err(SpeechEngineError::NotInitialized)
        ));
    }

    #[test]
    fn transcript_segment_carries_a_confidence_result() {
        let segment = TranscriptSegment {
            id: Uuid::new_v4(),
            sequence: 0,
            text: "Romans eight".into(),
            is_final: true,
            confidence: ConfidenceResult::new(0.9, ConfidenceSource::Model, None),
            start_ms: 0,
            end_ms: 500,
            language: Some("en".into()),
            speaker_id: None,
        };
        assert!(segment.confidence.is_auto_acceptable());
    }
}
